sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: J+OIMe/lPwvfmHxGfxEEUVU1DPNqUEYry2RQHI77UByFBQhrhK/7E3PMyOjD+Ty/D+fFXyaWLyd3SwJH8WB/xc7SouTVTxg44QIwAr3xn9BtYA+HuqRvmwB5hXSkKhRVQcuMqF4QT59TTkVA080mG4EYn8OlUzjG+4UZogRTG3KBp7rUyurAu+42S6bF6x3tUzt9Du5cPos2jxjEuOYqaqgxvv65rfv5kPVGibU1rf5nxsW2pQDpczV+uJ7LHSquzCKOPDLOiqxbGArb7RJrqLBCElynMf0fEZ2s+ZedVTQbrqyUJVkCUtcPYu+dRRx0CkmNTFUZk+WaQ5DO3SvUADltivTsE/eNjgbL8zQMF5l/IgSGDRntdxzCIOaN4jjeVy5MQeK6WRrjgdpMqOZM99QNi20s88e/Wu6rl8ya8ezKvROLIwjdZyGSAqQMeFz4ZXAhdeju5L7GIz6udoJWYB+g0fgZUUDEqa+0flc0io0eN+FvferjNcD8sXL7Cthm+mSqKwrsjIsyse2ZEXIKmR18qt8bXVn09XnQ0gbXqVQZ7LNkfKgG5ldn8RXDHYF29+u6XKVkpOufo4LqQj0aouZpd9FHsOWwLoM7fduJ1k+Gj1QYrqX1N5SAso/NPsjqtu9LyFK+XQFiONyhLAPBQpZzmajNjpwtco8yoygudVw=
  only:
  - master
